apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
    - port: 3000       # Service port (cluster IP)
      targetPort: 3000 # Container port
      nodePort: 31000  # External access on EC2 (via public IP)
